apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: obligatorio
type: Opaque
stringData:
  DB_HOST: "obligatorio-postgres.cew7vw1ul0vn.us-east-1.rds.amazonaws.com" 
  DB_USER: "appuser"          
  DB_PASSWORD: "obligatorio-infra" 
  DB_NAME: "obligatorio-postgres"   
  SECRET_KEY: "dev-secret"  
